/// <reference lib="webworker" />
declare const self: ServiceWorkerGlobalScope;

// Service worker configuration
// The actual service worker with routing is auto-generated by vite-plugin-pwa

// Handle install event
self.addEventListener('install', (event: ExtendableEvent) => {
  console.log('[SW] Install event');
  self.skipWaiting();
});

// Handle activate event
self.addEventListener('activate', (event: ExtendableEvent) => {
  console.log('[SW] Activate event');
  event.waitUntil(self.clients.claim());
});

// Handle fetch events (delegated to the auto-generated SW from vite-plugin-pwa)
self.addEventListener('fetch', (event: FetchEvent) => {
  // Default handling - the service worker generated by vite-plugin-pwa
  // will handle caching strategies
});

// Handle messages from clients
self.addEventListener('message', (event: ExtendableMessageEvent) => {
  console.log('[SW] Message received:', event.data);
  
  if (event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

export {};
