export interface CatalogSkill {
  name: string;
  category:
    | "PROGRAMMING_LANGUAGE"
    | "FRAMEWORK"
    | "DATABASE"
    | "TOOL"
    | "CLOUD"
    | "COMPUTER_SCIENCE"
    | "OTHER";
}

export const SKILL_CATALOG: CatalogSkill[] = [
  // Programming Languages
  { name: "Java", category: "PROGRAMMING_LANGUAGE" },
  { name: "Python", category: "PROGRAMMING_LANGUAGE" },
  { name: "C", category: "PROGRAMMING_LANGUAGE" },
  { name: "C++", category: "PROGRAMMING_LANGUAGE" },
  { name: "C#", category: "PROGRAMMING_LANGUAGE" },
  { name: "JavaScript", category: "PROGRAMMING_LANGUAGE" },
  { name: "TypeScript", category: "PROGRAMMING_LANGUAGE" },
  { name: "Go", category: "PROGRAMMING_LANGUAGE" },
  { name: "Rust", category: "PROGRAMMING_LANGUAGE" },
  { name: "Kotlin", category: "PROGRAMMING_LANGUAGE" },
  { name: "Swift", category: "PROGRAMMING_LANGUAGE" },
  { name: "PHP", category: "PROGRAMMING_LANGUAGE" },
  { name: "Ruby", category: "PROGRAMMING_LANGUAGE" },
  { name: "Scala", category: "PROGRAMMING_LANGUAGE" },
  { name: "Perl", category: "PROGRAMMING_LANGUAGE" },
  { name: "Dart", category: "PROGRAMMING_LANGUAGE" },
  { name: "R", category: "PROGRAMMING_LANGUAGE" },
  { name: "MATLAB", category: "PROGRAMMING_LANGUAGE" },
  { name: "Groovy", category: "PROGRAMMING_LANGUAGE" },
  { name: "Shell Scripting", category: "PROGRAMMING_LANGUAGE" },
  { name: "Bash", category: "PROGRAMMING_LANGUAGE" },
  { name: "PowerShell", category: "PROGRAMMING_LANGUAGE" },
  { name: "Lua", category: "PROGRAMMING_LANGUAGE" },
  { name: "Haskell", category: "PROGRAMMING_LANGUAGE" },
  { name: "Objective-C", category: "PROGRAMMING_LANGUAGE" },
  { name: "Visual Basic", category: "PROGRAMMING_LANGUAGE" },
  { name: "Julia", category: "PROGRAMMING_LANGUAGE" },
  { name: "Assembly", category: "PROGRAMMING_LANGUAGE" },
  { name: "COBOL", category: "PROGRAMMING_LANGUAGE" },
  { name: "Fortran", category: "PROGRAMMING_LANGUAGE" },
  { name: "Elixir", category: "PROGRAMMING_LANGUAGE" },
  { name: "Zig", category: "PROGRAMMING_LANGUAGE" },
  { name: "Mojo", category: "PROGRAMMING_LANGUAGE" },

  // Frameworks
  { name: "Spring", category: "FRAMEWORK" },
  { name: "Spring Boot", category: "FRAMEWORK" },
  { name: "Spring MVC", category: "FRAMEWORK" },
  { name: "Spring Security", category: "FRAMEWORK" },
  { name: "Spring Data JPA", category: "FRAMEWORK" },
  { name: "Spring Cloud", category: "FRAMEWORK" },
  { name: "Hibernate", category: "FRAMEWORK" },
  { name: "React", category: "FRAMEWORK" },
  { name: "React Native", category: "FRAMEWORK" },
  { name: "Angular", category: "FRAMEWORK" },
  { name: "Vue.js", category: "FRAMEWORK" },
  { name: "Nuxt.js", category: "FRAMEWORK" },
  { name: "Next.js", category: "FRAMEWORK" },
  { name: "Express.js", category: "FRAMEWORK" },
  { name: "Node.js", category: "FRAMEWORK" },
  { name: "NestJS", category: "FRAMEWORK" },
  { name: "Fastify", category: "FRAMEWORK" },
  { name: "Hono", category: "FRAMEWORK" },
  { name: "Flask", category: "FRAMEWORK" },
  { name: "Django", category: "FRAMEWORK" },
  { name: "FastAPI", category: "FRAMEWORK" },
  { name: "ASP.NET Core", category: "FRAMEWORK" },
  { name: "Laravel", category: "FRAMEWORK" },
  { name: "CodeIgniter", category: "FRAMEWORK" },
  { name: "Symfony", category: "FRAMEWORK" },
  { name: "Ruby on Rails", category: "FRAMEWORK" },
  { name: "Svelte", category: "FRAMEWORK" },
  { name: "SvelteKit", category: "FRAMEWORK" },
  { name: "SolidJS", category: "FRAMEWORK" },
  { name: "Astro", category: "FRAMEWORK" },
  { name: "Remix", category: "FRAMEWORK" },
  { name: "Qwik", category: "FRAMEWORK" },
  { name: "Tailwind CSS", category: "FRAMEWORK" },
  { name: "Bootstrap", category: "FRAMEWORK" },
  { name: "Material UI", category: "FRAMEWORK" },
  { name: "Chakra UI", category: "FRAMEWORK" },
  { name: "Ant Design", category: "FRAMEWORK" },
  { name: "jQuery", category: "FRAMEWORK" },
  { name: "Electron", category: "FRAMEWORK" },
  { name: "Qt", category: "FRAMEWORK" },

  // Databases
  { name: "MySQL", category: "DATABASE" },
  { name: "PostgreSQL", category: "DATABASE" },
  { name: "MariaDB", category: "DATABASE" },
  { name: "Oracle Database", category: "DATABASE" },
  { name: "Microsoft SQL Server", category: "DATABASE" },
  { name: "SQLite", category: "DATABASE" },
  { name: "MongoDB", category: "DATABASE" },
  { name: "Redis", category: "DATABASE" },
  { name: "Apache Cassandra", category: "DATABASE" },
  { name: "Neo4j", category: "DATABASE" },
  { name: "CouchDB", category: "DATABASE" },
  { name: "DynamoDB", category: "DATABASE" },
  { name: "Firebase", category: "DATABASE" },
  { name: "Supabase", category: "DATABASE" },
  { name: "Elasticsearch", category: "DATABASE" },
  { name: "InfluxDB", category: "DATABASE" },
  { name: "Amazon RDS", category: "DATABASE" },
  { name: "Amazon Aurora", category: "DATABASE" },
  { name: "H2 Database", category: "DATABASE" },
  { name: "Qdrant", category: "DATABASE" },
  { name: "Milvus", category: "DATABASE" },

  // Tools
  { name: "Git", category: "TOOL" },
  { name: "GitHub", category: "TOOL" },
  { name: "GitLab", category: "TOOL" },
  { name: "Bitbucket", category: "TOOL" },
  { name: "Docker", category: "TOOL" },
  { name: "Kubernetes", category: "TOOL" },
  { name: "Helm", category: "TOOL" },
  { name: "Terraform", category: "TOOL" },
  { name: "Ansible", category: "TOOL" },
  { name: "Jenkins", category: "TOOL" },
  { name: "GitHub Actions", category: "TOOL" },
  { name: "CircleCI", category: "TOOL" },
  { name: "Travis CI", category: "TOOL" },
  { name: "Azure DevOps", category: "TOOL" },
  { name: "Maven", category: "TOOL" },
  { name: "Gradle", category: "TOOL" },
  { name: "Apache Ant", category: "TOOL" },
  { name: "Postman", category: "TOOL" },
  { name: "Swagger", category: "TOOL" },
  { name: "OpenAPI", category: "TOOL" },
  { name: "SoapUI", category: "TOOL" },
  { name: "Insomnia", category: "TOOL" },
  { name: "IntelliJ IDEA", category: "TOOL" },
  { name: "VS Code", category: "TOOL" },
  { name: "Eclipse", category: "TOOL" },
  { name: "NetBeans", category: "TOOL" },
  { name: "Android Studio", category: "TOOL" },
  { name: "Xcode", category: "TOOL" },
  { name: "Linux", category: "TOOL" },
  { name: "Ubuntu", category: "TOOL" },
  { name: "CentOS", category: "TOOL" },
  { name: "Red Hat Enterprise Linux", category: "TOOL" },
  { name: "Windows Server", category: "TOOL" },
  { name: "Nginx", category: "TOOL" },
  { name: "Apache HTTP Server", category: "TOOL" },
  { name: "Apache Tomcat", category: "TOOL" },
  { name: "Kafka", category: "TOOL" },
  { name: "RabbitMQ", category: "TOOL" },
  { name: "ActiveMQ", category: "TOOL" },
  { name: "Prometheus", category: "TOOL" },
  { name: "Grafana", category: "TOOL" },
  { name: "SonarQube", category: "TOOL" },
  { name: "ELK Stack", category: "TOOL" },
  { name: "Logstash", category: "TOOL" },
  { name: "Kibana", category: "TOOL" },
  { name: "Splunk", category: "TOOL" },
  { name: "Figma", category: "TOOL" },
  { name: "Jira", category: "TOOL" },
  { name: "Confluence", category: "TOOL" },
  { name: "Trello", category: "TOOL" },
  { name: "Vite", category: "TOOL" },
  { name: "Bun", category: "TOOL" },
  { name: "pnpm", category: "TOOL" },

  // Cloud
  { name: "AWS", category: "CLOUD" },
  { name: "Amazon EC2", category: "CLOUD" },
  { name: "Amazon S3", category: "CLOUD" },
  { name: "Amazon ECS", category: "CLOUD" },
  { name: "Amazon EKS", category: "CLOUD" },
  { name: "AWS Lambda", category: "CLOUD" },
  { name: "AWS IAM", category: "CLOUD" },
  { name: "AWS CloudFormation", category: "CLOUD" },
  { name: "AWS CloudWatch", category: "CLOUD" },
  { name: "AWS Route 53", category: "CLOUD" },
  { name: "Azure", category: "CLOUD" },
  { name: "Azure App Service", category: "CLOUD" },
  { name: "Azure Functions", category: "CLOUD" },
  { name: "Azure Kubernetes Service", category: "CLOUD" },
  { name: "Google Cloud", category: "CLOUD" },
  { name: "Google Compute Engine", category: "CLOUD" },
  { name: "Google Kubernetes Engine", category: "CLOUD" },
  { name: "Google Cloud Storage", category: "CLOUD" },
  { name: "Firebase Hosting", category: "CLOUD" },
  { name: "Vercel", category: "CLOUD" },
  { name: "Netlify", category: "CLOUD" },
  { name: "Render", category: "CLOUD" },
  { name: "Railway", category: "CLOUD" },
  { name: "Fly.io", category: "CLOUD" },
  { name: "Heroku", category: "CLOUD" },
  { name: "DigitalOcean", category: "CLOUD" },
  { name: "Cloudflare", category: "CLOUD" },
  { name: "Oracle Cloud", category: "CLOUD" },
  { name: "IBM Cloud", category: "CLOUD" },
  { name: "Alibaba Cloud", category: "CLOUD" },

  // Computer Science
  { name: "Data Structures", category: "COMPUTER_SCIENCE" },
  { name: "Algorithms", category: "COMPUTER_SCIENCE" },
  { name: "Object-Oriented Programming", category: "COMPUTER_SCIENCE" },
  { name: "Functional Programming", category: "COMPUTER_SCIENCE" },
  { name: "DBMS", category: "COMPUTER_SCIENCE" },
  { name: "Operating Systems", category: "COMPUTER_SCIENCE" },
  { name: "Computer Networks", category: "COMPUTER_SCIENCE" },
  { name: "System Design", category: "COMPUTER_SCIENCE" },
  { name: "Low Level Design", category: "COMPUTER_SCIENCE" },
  { name: "High Level Design", category: "COMPUTER_SCIENCE" },
  { name: "Microservices", category: "COMPUTER_SCIENCE" },
  { name: "GraphQL", category: "COMPUTER_SCIENCE" },
  { name: "gRPC", category: "COMPUTER_SCIENCE" },
  { name: "SOAP", category: "COMPUTER_SCIENCE" },
  { name: "JWT", category: "COMPUTER_SCIENCE" },
  { name: "OAuth2", category: "COMPUTER_SCIENCE" },
  { name: "OpenID Connect", category: "COMPUTER_SCIENCE" },
  { name: "Design Patterns", category: "COMPUTER_SCIENCE" },
  { name: "SOLID Principles", category: "COMPUTER_SCIENCE" },
  { name: "Monolithic Architecture", category: "COMPUTER_SCIENCE" },
  { name: "Event-Driven Architecture", category: "COMPUTER_SCIENCE" },
  { name: "Distributed Systems", category: "COMPUTER_SCIENCE" },
  { name: "Caching", category: "COMPUTER_SCIENCE" },
  { name: "Load Balancing", category: "COMPUTER_SCIENCE" },
  { name: "Message Queues", category: "COMPUTER_SCIENCE" },
  { name: "Concurrency", category: "COMPUTER_SCIENCE" },
  { name: "Multithreading", category: "COMPUTER_SCIENCE" },
  { name: "Parallel Programming", category: "COMPUTER_SCIENCE" },
  { name: "Memory Management", category: "COMPUTER_SCIENCE" },
  { name: "Garbage Collection", category: "COMPUTER_SCIENCE" },
  { name: "TCP/IP", category: "COMPUTER_SCIENCE" },
  { name: "HTTP", category: "COMPUTER_SCIENCE" },
  { name: "HTTPS", category: "COMPUTER_SCIENCE" },
  { name: "DNS", category: "COMPUTER_SCIENCE" },
  { name: "WebSockets", category: "COMPUTER_SCIENCE" },
  { name: "CI/CD", category: "COMPUTER_SCIENCE" },
  { name: "Agile", category: "COMPUTER_SCIENCE" },
  { name: "Scrum", category: "COMPUTER_SCIENCE" },
  { name: "Kanban", category: "COMPUTER_SCIENCE" },
  { name: "Unit Testing", category: "COMPUTER_SCIENCE" },
  { name: "Integration Testing", category: "COMPUTER_SCIENCE" },
  { name: "Performance Testing", category: "COMPUTER_SCIENCE" },
  { name: "API Testing", category: "COMPUTER_SCIENCE" },
  { name: "Authentication", category: "COMPUTER_SCIENCE" },
  { name: "Authorization", category: "COMPUTER_SCIENCE" },
  { name: "Encryption", category: "COMPUTER_SCIENCE" },
  { name: "Cryptography", category: "COMPUTER_SCIENCE" },
  { name: "Software Engineering", category: "COMPUTER_SCIENCE" },
  { name: "Software Architecture", category: "COMPUTER_SCIENCE" },

  // Other
  { name: "Machine Learning", category: "OTHER" },
  { name: "Deep Learning", category: "OTHER" },
  { name: "Artificial Intelligence", category: "OTHER" },
  { name: "Natural Language Processing", category: "OTHER" },
  { name: "Computer Vision", category: "OTHER" },
  { name: "Data Science", category: "OTHER" },
  { name: "Data Analytics", category: "OTHER" },
  { name: "Big Data", category: "OTHER" },
  { name: "Apache Spark", category: "OTHER" },
  { name: "Apache Hadoop", category: "OTHER" },
  { name: "TensorFlow", category: "OTHER" },
  { name: "PyTorch", category: "OTHER" },
  { name: "Keras", category: "OTHER" },
  { name: "Scikit-learn", category: "OTHER" },
  { name: "Pandas", category: "OTHER" },
  { name: "NumPy", category: "OTHER" },
  { name: "Matplotlib", category: "OTHER" },
  { name: "OpenCV", category: "OTHER" },
  { name: "Hugging Face", category: "OTHER" },
  { name: "OpenAI API", category: "OTHER" },
  { name: "Claude API", category: "OTHER" },
  { name: "Gemini API", category: "OTHER" },
  { name: "LangChain", category: "OTHER" },
  { name: "LangGraph", category: "OTHER" },
  { name: "LlamaIndex", category: "OTHER" },
  { name: "Prompt Engineering", category: "OTHER" },
  { name: "RAG", category: "OTHER" },
  { name: "Vector Databases", category: "OTHER" },
  { name: "Pinecone", category: "OTHER" },
  { name: "ChromaDB", category: "OTHER" },
  { name: "Weaviate", category: "OTHER" },
  { name: "Blockchain", category: "OTHER" },
  { name: "Ethereum", category: "OTHER" },
  { name: "Solidity", category: "OTHER" },
  { name: "Web3", category: "OTHER" },
  { name: "Smart Contracts", category: "OTHER" },
  { name: "Android Development", category: "OTHER" },
  { name: "iOS Development", category: "OTHER" },
  { name: "Flutter", category: "OTHER" },
  { name: "Xamarin", category: "OTHER" },
  { name: "Unity", category: "OTHER" },
  { name: "Unreal Engine", category: "OTHER" },
  { name: "Ollama", category: "OTHER" },
  { name: "vLLM", category: "OTHER" },
];
