export interface CatalogSkill {
  name: string;
  category: "PROGRAMMING_LANGUAGE" | "FRAMEWORK" | "DATABASE" | "TOOL" | "CLOUD" | "COMPUTER_SCIENCE" | "OTHER";
}

export const SKILL_CATALOG: CatalogSkill[] = [
  // Programming Languages
  { name: "Java", category: "PROGRAMMING_LANGUAGE" },
  { name: "Python", category: "PROGRAMMING_LANGUAGE" },
  { name: "C", category: "PROGRAMMING_LANGUAGE" },
  { name: "C++", category: "PROGRAMMING_LANGUAGE" },
  { name: "JavaScript", category: "PROGRAMMING_LANGUAGE" },
  { name: "TypeScript", category: "PROGRAMMING_LANGUAGE" },
  { name: "Go", category: "PROGRAMMING_LANGUAGE" },
  { name: "Kotlin", category: "PROGRAMMING_LANGUAGE" },
  { name: "Swift", category: "PROGRAMMING_LANGUAGE" },
  { name: "PHP", category: "PROGRAMMING_LANGUAGE" },
  { name: "Rust", category: "PROGRAMMING_LANGUAGE" },
  { name: "Ruby", category: "PROGRAMMING_LANGUAGE" },
  { name: "Scala", category: "PROGRAMMING_LANGUAGE" },
  { name: "HTML5", category: "PROGRAMMING_LANGUAGE" },
  { name: "CSS3", category: "PROGRAMMING_LANGUAGE" },
  { name: "SQL", category: "PROGRAMMING_LANGUAGE" },
  { name: "Perl", category: "PROGRAMMING_LANGUAGE" },
  { name: "Bash", category: "PROGRAMMING_LANGUAGE" },
  { name: "PowerShell", category: "PROGRAMMING_LANGUAGE" },
  { name: "Dart", category: "PROGRAMMING_LANGUAGE" },
  { name: "R", category: "PROGRAMMING_LANGUAGE" },
  { name: "Julia", category: "PROGRAMMING_LANGUAGE" },
  { name: "Haskell", category: "PROGRAMMING_LANGUAGE" },
  { name: "Objective-C", category: "PROGRAMMING_LANGUAGE" },
  { name: "Assembly", category: "PROGRAMMING_LANGUAGE" },
  { name: "Lua", category: "PROGRAMMING_LANGUAGE" },

  // Frameworks
  { name: "Spring Boot", category: "FRAMEWORK" },
  { name: "Spring MVC", category: "FRAMEWORK" },
  { name: "Spring Security", category: "FRAMEWORK" },
  { name: "Hibernate", category: "FRAMEWORK" },
  { name: "React", category: "FRAMEWORK" },
  { name: "Angular", category: "FRAMEWORK" },
  { name: "Vue", category: "FRAMEWORK" },
  { name: "Svelte", category: "FRAMEWORK" },
  { name: "Astro", category: "FRAMEWORK" },
  { name: "Express", category: "FRAMEWORK" },
  { name: "Node.js", category: "FRAMEWORK" },
  { name: "Next.js", category: "FRAMEWORK" },
  { name: "Nuxt.js", category: "FRAMEWORK" },
  { name: "NestJS", category: "FRAMEWORK" },
  { name: "Flask", category: "FRAMEWORK" },
  { name: "Django", category: "FRAMEWORK" },
  { name: "FastAPI", category: "FRAMEWORK" },
  { name: "Laravel", category: "FRAMEWORK" },
  { name: "Ruby on Rails", category: "FRAMEWORK" },
  { name: "ASP.NET Core", category: "FRAMEWORK" },
  { name: "Gin", category: "FRAMEWORK" },
  { name: "Fiber", category: "FRAMEWORK" },
  { name: "Flutter", category: "FRAMEWORK" },
  { name: "React Native", category: "FRAMEWORK" },
  { name: "Xamarin", category: "FRAMEWORK" },
  { name: "TailwindCSS", category: "FRAMEWORK" },
  { name: "Bootstrap", category: "FRAMEWORK" },
  { name: "jQuery", category: "FRAMEWORK" },
  { name: "Remix", category: "FRAMEWORK" },
  { name: "SolidJS", category: "FRAMEWORK" },

  // Databases
  { name: "PostgreSQL", category: "DATABASE" },
  { name: "MySQL", category: "DATABASE" },
  { name: "MongoDB", category: "DATABASE" },
  { name: "Oracle", category: "DATABASE" },
  { name: "Redis", category: "DATABASE" },
  { name: "SQLite", category: "DATABASE" },
  { name: "Firebase", category: "DATABASE" },
  { name: "Cassandra", category: "DATABASE" },
  { name: "DynamoDB", category: "DATABASE" },
  { name: "Elasticsearch", category: "DATABASE" },
  { name: "Neo4j", category: "DATABASE" },
  { name: "CouchDB", category: "DATABASE" },
  { name: "MariaDB", category: "DATABASE" },
  { name: "MS SQL Server", category: "DATABASE" },
  { name: "InfluxDB", category: "DATABASE" },
  { name: "ClickHouse", category: "DATABASE" },

  // Tools
  { name: "Git", category: "TOOL" },
  { name: "GitHub", category: "TOOL" },
  { name: "GitLab", category: "TOOL" },
  { name: "Docker", category: "TOOL" },
  { name: "Kubernetes", category: "TOOL" },
  { name: "Maven", category: "TOOL" },
  { name: "Gradle", category: "TOOL" },
  { name: "Jenkins", category: "TOOL" },
  { name: "Postman", category: "TOOL" },
  { name: "IntelliJ IDEA", category: "TOOL" },
  { name: "VS Code", category: "TOOL" },
  { name: "Linux", category: "TOOL" },
  { name: "Vite", category: "TOOL" },
  { name: "Webpack", category: "TOOL" },
  { name: "npm", category: "TOOL" },
  { name: "pnpm", category: "TOOL" },
  { name: "yarn", category: "TOOL" },
  { name: "Ansible", category: "TOOL" },
  { name: "Terraform", category: "TOOL" },
  { name: "Prometheus", category: "TOOL" },
  { name: "Grafana", category: "TOOL" },
  { name: "Wireshark", category: "TOOL" },
  { name: "Figma", category: "TOOL" },
  { name: "JIRA", category: "TOOL" },
  { name: "Confluence", category: "TOOL" },
  { name: "CircleCI", category: "TOOL" },
  { name: "TravisCI", category: "TOOL" },

  // Cloud
  { name: "AWS", category: "CLOUD" },
  { name: "Azure", category: "CLOUD" },
  { name: "Google Cloud", category: "CLOUD" },
  { name: "Vercel", category: "CLOUD" },
  { name: "Render", category: "CLOUD" },
  { name: "Netlify", category: "CLOUD" },
  { name: "Heroku", category: "CLOUD" },
  { name: "Supabase", category: "CLOUD" },
  { name: "Cloudflare", category: "CLOUD" },
  { name: "DigitalOcean", category: "CLOUD" },
  { name: "OpenStack", category: "CLOUD" },

  // Computer Science
  { name: "Data Structures", category: "COMPUTER_SCIENCE" },
  { name: "Algorithms", category: "COMPUTER_SCIENCE" },
  { name: "Object-Oriented Programming", category: "COMPUTER_SCIENCE" },
  { name: "DBMS", category: "COMPUTER_SCIENCE" },
  { name: "Operating Systems", category: "COMPUTER_SCIENCE" },
  { name: "Computer Networks", category: "COMPUTER_SCIENCE" },
  { name: "REST APIs", category: "COMPUTER_SCIENCE" },
  { name: "JWT", category: "COMPUTER_SCIENCE" },
  { name: "OAuth2", category: "COMPUTER_SCIENCE" },
  { name: "Design Patterns", category: "COMPUTER_SCIENCE" },
  { name: "System Design", category: "COMPUTER_SCIENCE" },
  { name: "Microservices", category: "COMPUTER_SCIENCE" },
  { name: "Machine Learning", category: "COMPUTER_SCIENCE" },
  { name: "Artificial Intelligence", category: "COMPUTER_SCIENCE" },
  { name: "CI/CD", category: "COMPUTER_SCIENCE" },
  { name: "Agile Methodology", category: "COMPUTER_SCIENCE" },
  { name: "Scrum", category: "COMPUTER_SCIENCE" },
  { name: "Cryptography", category: "COMPUTER_SCIENCE" },
  { name: "Blockchain", category: "COMPUTER_SCIENCE" },
  { name: "Unit Testing", category: "COMPUTER_SCIENCE" },
  { name: "Integration Testing", category: "COMPUTER_SCIENCE" },
  { name: "DevOps", category: "COMPUTER_SCIENCE" },
  { name: "Functional Programming", category: "COMPUTER_SCIENCE" },
  { name: "SDLC", category: "COMPUTER_SCIENCE" },
];
