import { ThemePreset } from "../types";

export const brutalistTheme: ThemePreset = {
  id: "brutalist",
  name: "Brutalist",
  pageBg: "bg-[#eae6e1] text-black font-mono font-bold",
  card: "bg-white border-3 border-black rounded-none shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:translate-x-[-2px] hover:translate-y-[-2px] hover:shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] transition-all duration-200 text-black",
  cardHeader: "border-b-3 border-black bg-white px-6 py-4",
  buttonPrimary: "bg-[#38bdf8] hover:bg-[#0ea5e9] text-black border-3 border-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] hover:translate-x-[-1px] hover:translate-y-[-1px] hover:shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] transition-all duration-150 active:translate-x-[1px] active:translate-y-[1px] active:shadow-[1px_1px_0px_rgba(0,0,0,1)] uppercase font-black tracking-widest rounded-none",
  buttonSecondary: "bg-white hover:bg-slate-100 text-black border-3 border-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] hover:translate-x-[-1px] hover:translate-y-[-1px] hover:shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] transition-all duration-150 active:translate-x-[1px] active:translate-y-[1px] active:shadow-[1px_1px_0px_rgba(0,0,0,1)] uppercase font-black tracking-widest rounded-none",
  input: "bg-white border-3 border-black rounded-none font-bold text-black focus:outline-none focus:bg-yellow-50 focus:ring-0",
  badgeGreen: "bg-[#4ade80] text-black border-2 border-black shadow-[2px_2px_0px_rgba(0,0,0,1)] rounded-none px-2 font-black",
  badgeOrange: "bg-[#fb923c] text-black border-2 border-black shadow-[2px_2px_0px_rgba(0,0,0,1)] rounded-none px-2 font-black",
  badgeRed: "bg-[#f87171] text-black border-2 border-black shadow-[2px_2px_0px_rgba(0,0,0,1)] rounded-none px-2 font-black",
  textColor: "text-black",
  headingColor: "text-black font-black uppercase",
  accentText: "text-black underline decoration-[#38bdf8] decoration-4",
  accentBg: "bg-black text-white",
  tableHeaderClass: "bg-white border-b-3 border-black text-black uppercase font-bold",
  tableRowClass: "hover:bg-[#f1ebe5] border-b-2 border-black/10",
  tableCellClass: "text-black font-bold",
  sidebarBg: "bg-white border-r-3 border-black text-black",
  emptyStateClass: "bg-white border-3 border-black shadow-[2px_2px_0px_rgba(0,0,0,1)] rounded-none",
  loadingStateClass: "border-2 border-black bg-slate-100 h-6 rounded-none animate-pulse",
  containerClass: "container font-mono font-bold",
  chartTheme: {
    grid: "#000000",
    text: "#000000",
    colors: ["#38bdf8", "#4ade80", "#fb923c", "#f87171", "#a78bfa"],
  },
  navbarBg: "bg-white border-b-3 border-black text-black font-mono",
  navActive: "bg-[#ffde43] text-black border-2 border-black shadow-[2px_2px_0px_rgba(0,0,0,1)] rounded-none font-black",
  navInactive: "text-black hover:bg-slate-100 rounded-none font-black",
};
