spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: event-app-tracker

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/event_tracker_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:****}

  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user
        provider:
          github:
            user-info-uri: https://api.github.com/user
            user-name-attribute: name

server:
  port: 8080
  forward-headers-strategy: native
app:
  jwt:
    secret: ${JWT_SECRET:this-is-a-very-long-secret-key-that-is-at-least-64-characters-long-to-satisfy-hs512-requirements}
    expiration: 1296000000

  frontend-url: ${FRONTEND_URL:http://localhost:5173}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,https://eventpulse-phi.vercel.app}
